name: Android CI (Daily Authenticated)

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          MAVEN_CENTRAL_USERNAME:           ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD:           ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_STAGING_PROFILE_ID: '8ecc3ea87441e'
          MAVEN_CENTRAL_SIGNING_KEY_ID:     '0x9100B73AD09BAC64'
          AULFA_GITHUB_ACCESS_TOKEN:        ${{ secrets.AULFA_GITHUB_ACCESS_TOKEN }}
        run: .ci/ci-main.sh normal
